import type { Metadata } from 'next';
// import localFont from "next/font/local";
import '../globals.css';
import GlobalProvider from '@/contexts/globlaProvider';
import Root from './root';
import Navbar from '@/components/navbar/navbar';
import Footer from './components/footer';

// const geistSans = localFont({
//   src: "../assets/fonts/",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
    title: 'Ecommerce Template',
    description: 'Generated by Kais Al Husrom',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <GlobalProvider>
            <Root>
                <Navbar />
                {children}
                <Footer />
            </Root>
        </GlobalProvider>
    );
}
